
package cn.tyc.bos.service;

import cn.tyc.bos.domain.Order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOrderService", targetNamespace = "http://take_delivery.service.bos.tyc.com/")
@XmlSeeAlso({

})
public interface IOrderService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://take_delivery.service.bos.tyc.com/", className = "com.tyc.bos.service.take_delivery.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://take_delivery.service.bos.tyc.com/", className = "com.tyc.bos.service.take_delivery.SaveResponse")
    public void save(
            @WebParam(name = "arg0", targetNamespace = "")
                    Order arg0);

}
